server:
  address: 127.0.0.1
  port : 8081
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/sgrunt
    username: sgrunt
    password: sgrunt

springdoc:
  swagger-ui:
    path: /sgrunty/swagger-ui.html
    config-url: /sgrunty/v3/api-docs/swagger-config
    url: /sgrunty/v3/api-docs
  api-docs:
    path: /sgrunty/v3/api-docs

sgruntbot:
  config:
    chat-id: -1001103213994
    telegram-token-file: token.txt
    baseRestUrl: https://giambo.ch
