name: Deploy SgruntBot

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Increase Patch version
        run: |
          ./gradlew incrementVersion --versionIncrementType=PATCH
          echo "SGRUNT_VERSION=$(./gradlew printVersion | grep "Version:" | awk '{print $2}')" >> $GITHUB_ENV
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update PATCH Version to ${{ env.SGRUNT_VERSION }} [skip actions]
          branch: master
      - name: Pull, build and restart SgruntBot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/SgruntBot
            git pull
            kill "$(cat run.pid)"
            ./gradlew bootJar
            nohup java -jar build/libs/sgruntbot-${{ env.SGRUNT_VERSION }}.jar > out.log 2>error.log & echo $! > run.pid
